name: Continuous Integration

on:
  push:
    branches:
     - main
     - master
     - next
     - 'v*'
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

env:
  TZ: 'UTC'

jobs:
  test:
    uses: fastify/workflows/.github/workflows/plugins-ci.yml@29329a13c391edeae7d2aa401cbf7664ef830393
    with:
      lint: true
      license-check: true
